CREATE TABLE auteur(
   id_auteur INT AUTO_INCREMENT,
   nom VARCHAR(250)  NOT NULL,
   email VARCHAR(250) ,
   role VARCHAR(150) ,
   PRIMARY KEY(id_auteur)
);

CREATE TABLE type_article(
   id_type INT AUTO_INCREMENT,
   libelle VARCHAR(150)  NOT NULL,
   PRIMARY KEY(id_type)
);

CREATE TABLE utilisateur(
   id_utilisateur INT AUTO_INCREMENT,
   email VARCHAR(250) ,
   mot_de_passe VARCHAR(50)  NOT NULL,
   PRIMARY KEY(id_utilisateur)
);

CREATE TABLE article(
   id_article INT AUTO_INCREMENT,
   titre VARCHAR(250)  NOT NULL,
   meta_description VARCHAR(255)  NOT NULL,
   contenu TEXT NOT NULL,
   mot_cle_principal VARCHAR(255)  NOT NULL,
   mot_cle_secondaire VARCHAR(255)  NOT NULL,
   priorite BOOLEAN,
   nombre_vue INT,
   img_src VARCHAR(255)  NOT NULL,
   img_alt VARCHAR(250)  NOT NULL,
   date_publication DATETIME NOT NULL,
   id_auteur INT NOT NULL,
   id_type INT NOT NULL,
   PRIMARY KEY(id_article),
   FOREIGN KEY(id_auteur) REFERENCES auteur(id_auteur),
   FOREIGN KEY(id_type) REFERENCES type_article(id_type)
);

CREATE TABLE media(
   id_media INT AUTO_INCREMENT,
   src VARCHAR(250)  NOT NULL,
   alt VARCHAR(250)  NOT NULL,
   id_article INT NOT NULL,
   paragraphe INT,
   PRIMARY KEY(id_media),
   FOREIGN KEY(id_article) REFERENCES article(id_article)
);

INSERT INTO type_article (libelle) VALUES
('Analyse'),
('Reportage'),
('Interview'),
('Rapport');

INSERT INTO auteur (nom, email, role) VALUES
('Jean Rakoto', 'jean.rakoto@gmail.com', 'journaliste'),
('Marie Andriam', 'marie.andriam@gmail.com', 'redacteur'),
('Paul Raveloson', 'paul.raveloson@gmail.com', 'journaliste'),
('Sarah Rasoanaivo', 'sarah.rasoanaivo@gmail.com', 'reporter'),
('Hery Ando', 'hery.ando@gmail.com', 'editor'),
('Lalao Razaf', 'lalao.razaf@gmail.com', 'journaliste'),
('Andry Solo', 'andry.solo@gmail.com', 'redacteur'),
('Nina Rak', 'nina.rak@gmail.com', 'reporter'),
('Tiana Rabe', 'tiana.rabe@gmail.com', 'journaliste'),
('Faly Raja', 'faly.raja@gmail.com', 'editor');

INSERT INTO utilisateur (email, mot_de_passe)
VALUES (
  'admin@gmail.com',
  '$2y$12$7akwUil6/uysoWqeay9bNOjZ8aePk.2PDo/Fh8dL/uKcPbWmCvNQ2'
);

INSERT INTO article (titre, meta_description, contenu, mot_cle_principal, mot_cle_secondaire, priorite, nombre_vue, img_src, img_alt, date_publication, id_auteur, id_type) VALUES
('Iran: Les dessous de la stratégie militaire de Téhéran', 'Découvrez les coulisses de la stratégie militaire iranienne. Une analyse approfondie des forces et faiblesses de Téhéran dans le conflit.', '<h2>Contexte géopolitique actuel</h2><p>La guerre en Iran ne se limite pas à un affrontement territorial. Elle révèle des années de tensions diplomatiques et économiques. Les alliances régionales jouent un rôle clé dans l''évolution du conflit.</p><h2>Capacités militaires iraniennes</h2><p>L''Iran a développé une doctrine militaire hybride combinant forces conventionnelles, missiles balistiques et soutien à des groupes alliés. Cette approche vise à dissuader toute attaque directe tout en projetant son influence.</p><blockquote>Selon un expert du CSIS, "l''arsenal de missiles iraniens est l''un des plus diversifiés au Moyen-Orient".</blockquote><h2>Faiblesses structurelles</h2><p>Malgré ses atouts, l''Iran fait face à des défis internes : sanctions économiques, tensions sociales et équipements vieillissants. Ces facteurs limitent sa capacité à soutenir un conflit prolongé.</p>', 'stratégie militaire Iran', 'géopolitique Iran,doctrine militaire,missiles balistiques,alliances régionales,sanctions économiques,forces conventionnelles,tensions diplomatiques', TRUE, 1240, 'image-29.jpg', 'stratégie militaire Iran analyse', '2026-02-10 08:00:00', 1, 1),
('Iran: Reportage au cœur des villes bombardées', 'Immersion exclusive dans les zones dévastées. Témoignages poignants de civils et images chocs. Un reportage sans filtre.', '<h2>Dans les ruines d''Ispahan</h2><p>Les rues autrefois animées ne sont plus que gravats. Les habitants racontent les nuits de bombardements. "On ne dort plus, chaque bruit nous fait trembler", confie Ali, 45 ans.</p><h2>L''hôpital de campagne</h2><p>Faute de structures suffisantes, un gymnase a été transformé en centre de soins d''urgence. Les médecins travaillent 20 heures par jour avec des ressources limitées.</p><blockquote>"Nous sauvons des vies avec des moyens du passé, mais nous ne lâcherons rien", déclare le Dr. Fatima.</blockquote><h2>La solidarité malgré tout</h2><p>Dans ce chaos, des réseaux de voisins s''organisent pour distribuer nourriture et médicaments. La résilience iranienne se manifeste dans chaque geste d''entraide.</p>', 'bombardements Iran', 'civils Iran,crise humanitaire,hôpital de campagne,ruines Ispahan,solidarité iranienne,bombardements nuit,médecins urgence', FALSE, 982, 'image-08.jpg', 'reportage bombardements Iran civil', '2026-02-12 10:30:00', 2, 2),
('Iran: Interview exclusive d''un général dissident', 'Un haut gradé iranien parle pour la première fois. Révélations sur les pertes réelles et les divisions internes de l''armée.', '<h2>Les raisons de son départ</h2><p>Le général en retraite Reza Karimi explique pourquoi il a quitté l''armée après 30 ans de service. "Je ne pouvais plus être complice d''une guerre qui détruit mon pays sans objectif clair."</p><h2>Pertes sous-estimées</h2><p>Selon lui, les chiffres officiels minimisent de 40% les pertes humaines. Il pointe une mauvaise planification logistique et des frappes mal ciblées.</p><blockquote>"Notre commandement ignore les réalités du terrain. On envoie des jeunes sans formation suffisante", affirme-t-il.</blockquote><h2>Divisions internes</h2><p>Il révèle l''existence de deux clans au sein du haut commandement : les partisans d''une ligne dure et ceux favorables à une sortie de crise négociée. Cette fracture paralyse les décisions stratégiques.</p>', 'armée Iran divisions', 'général dissident Iran,pertes militaires,commandement iranien,crise interne armée,sortie de crise,logistique militaire,frappes mal ciblées', TRUE, 1560, 'image-21.jpg', 'interview général dissident Iran', '2026-02-14 09:15:00', 3, 3),
('Iran: Rapport sur l''impact économique de la guerre', 'Analyse chiffrée des conséquences économiques. PIB, inflation, chômage : l''effondrement accéléré par le conflit.', '<h2>Contraction du PIB</h2><p>Le PIB iranien a chuté de 12% en un an selon les dernières données. Les secteurs pétrolier et agricole sont les plus touchés. Les exportations ont diminué de moitié.</p><h2>Inflation galopante</h2><p>Le taux d''inflation dépasse désormais 55%, rendant l''accès aux produits de première nécessité impossible pour une large partie de la population. Le rial a perdu 70% de sa valeur.</p><blockquote>"C''est une classe moyenne qui disparaît", explique un économiste de Téhéran.</blockquote><h2>Chômage et migration</h2><p>Le taux de chômage chez les jeunes atteint 35%. Des milliers de jeunes diplômés cherchent à quitter le pays, provoquant une fuite des cerveaux sans précédent.</p>', 'économie Iran guerre', 'PIB Iran,inflation Iran,chômage Iran,rial iranien,migration Iran,crise économique,secteurs touchés', FALSE, 875, 'image-25.jpg', 'rapport économie Iran guerre', '2026-02-16 14:00:00', 4, 4),
('Iran: Analyse des alliances régionales', 'Comment l''Iran utilise ses alliés pour étendre son influence. Liban, Yémen, Syrie : les ramifications du conflit.', '<h2>Le Hezbollah libanais</h2><p>Le Hezbollah est devenu un prolongement opérationnel de l''Iran. Il fournit une capacité de frappe asymétrique et une pression politique sur Israël.</p><h2>Les Houthis au Yémen</h2><p>Le soutien iranien aux Houthis lui permet de menacer les routes maritimes et de peser sur l''Arabie saoudite. Une stratégie de contournement efficace.</p><blockquote>Un analyste note : "L''axe de la résistance est l''outil principal de projection de puissance iranienne."</blockquote><h2>Syrie : pont terrestre stratégique</h2><p>Le corridor terrestre via l''Irak et la Syrie assure un approvisionnement continu en armes et renforce l''ancrage régional de Téhéran.</p>', 'alliances Iran', 'Hezbollah Iran,Houthis Iran,axe résistance,Syrie Iran,projection puissance,stratégie contournement,alliances régionales Iran', TRUE, 1120, 'image-23.jpg', 'analyse alliances régionales Iran', '2026-02-18 11:20:00', 5, 1),
('Iran: Reportage sur les réfugiés afghans pris dans la guerre', 'Des milliers d''Afghans vivant en Iran sont aujourd''hui pris au piège. Témoignages et conditions de vie dramatiques.', '<h2>Double peine pour les réfugiés</h2><p>Déjà vulnérables, les réfugiés afghans subissent les bombardements sans aucune protection. Ils sont souvent accusés à tort d''être des espions.</p><h2>Villes dortoirs de Téhéran</h2><p>Dans les quartiers sud de la capitale, la promiscuité est extrême. L''accès à l''eau potable et aux soins est devenu un luxe.</p><blockquote>"Nous avons fui l''Afghanistan pour trouver la paix, ici nous trouvons la même guerre", raconte Fatima, mère de trois enfants.</blockquote><h2>Réseaux d''aide informels</h2><p>Face à l''inaction des autorités, des volontaires iraniens et afghans se mobilisent pour distribuer des repas et des vêtements.</p>', 'réfugiés Iran guerre', 'Afghans Iran,réfugiés pris au piège,conditions de vie,bombardements Téhéran,espions accusés,aide informelle,villes dortoirs', FALSE, 743, 'image-14.jpg', 'reportage réfugiés afghans Iran', '2026-02-20 08:45:00', 6, 2),
('Iran: Interview d''une ONG opérant en zone de conflit', 'Les défis de l''aide humanitaire face aux restrictions. Témoignage poignant d''un coordinateur d''urgence.', '<h2>Accès limité aux zones sinistrées</h2><p>Les autorités imposent des autorisations longues et souvent refusées. Les équipes peuvent attendre des semaines avant d''intervenir, au détriment des populations.</p><h2>Détournement de l''aide</h2><p>L''ONG dénonce des tentatives de récupération politique des convois humanitaires par des groupes armés liés au gouvernement.</p><blockquote>"Notre mission est médicale, on nous demande parfois de soutenir des messages politiques. C''est inacceptable", témoigne le coordinateur.</blockquote><h2>Bénévoles locaux héroïques</h2><p>Malgré les risques, des dizaines de jeunes Iraniens rejoignent l''ONG pour aider leurs voisins. Un élan citoyen précieux.</p>', 'aide humanitaire Iran', 'ONG Iran,restrictions humanitaires,détournement aide,bénévoles Iran,accès sinistrés,convois humanitaires,coordination urgence', TRUE, 928, 'image-27.jpg', 'interview ONG aide humanitaire Iran', '2026-02-22 15:30:00', 7, 3),
('Iran: Rapport sur les pertes en équipements militaires', 'Bilan détaillé des blindés, drones et systèmes de défense détruits. L''impact sur la capacité de combat iranienne.', '<h2>Drones : un avantage érodé</h2><p>L''Iran a perdu plus de 200 drones depuis le début du conflit, soit environ un tiers de sa flotte. Les systèmes de contre-mesures adverses se sont améliorés.</p><h2>Blindés et artillerie</h2><p>Les images satellites montrent des centaines de chars T-72 et BMP mis hors service. La logistique de réparation est défaillante.</p><blockquote>"L''armée iranienne n''a pas anticipé l''usure rapide de son matériel", indique un rapport de l''IISS.</blockquote><h2>Systèmes de défense aérienne</h2><p>Des frappes ciblées ont détruit plusieurs batteries S-300, créant des brèches dans la couverture aérienne du pays.</p>', 'pertes militaires Iran', 'drones Iran,blindés Iran,défense aérienne,S-300 Iran,usure matériel,frappes ciblées,pertes équipements', FALSE, 632, 'image-21.jpg', 'rapport pertes équipements Iran', '2026-02-24 10:00:00', 8, 4),
('Iran: Analyse de la propagande et contrôle médiatique', 'Comment le régime manipule l''information. Médias, réseaux sociaux, désinformation : les mécanismes du mensonge d''État.', '<h2>Médias traditionnels sous tutelle</h2><p>Les chaînes de télévision nationales diffusent en boucle des images de victoires supposées. Toute critique est censurée.</p><h2>Armée de trolls et bots</h2><p>Des milliers de faux comptes amplifient les discours pro-régime et attaquent les opposants sur Telegram et Twitter.</p><blockquote>"C''est une guerre cognitive où la réalité est constamment déformée", explique un chercheur en sciences politiques.</blockquote><h2>Blocage des médias indépendants</h2><p>Les sites d''information étrangers sont régulièrement filtrés. Les journalistes locaux risquent l''emprisonnement pour "atteinte à la sécurité nationale".</p>', 'propagande Iran', 'contrôle médiatique Iran,désinformation Iran,censure Iran,trolls Iran,guerre cognitive,médias indépendants', TRUE, 1305, 'image-07.jpg', 'analyse propagande Iran', '2026-02-26 13:45:00', 9, 1),
('Iran: Reportage sur les manifestations anti-guerre', 'Malgré la répression, des voix s''élèvent contre le conflit. Récits de manifestants et de familles de soldats.', '<h2>Les mères de soldats brisent le silence</h2><p>Chaque semaine, un petit groupe de femmes se rassemble pour réclamer le retour de leurs enfants. Elles sont rapidement dispersées par les forces de l''ordre.</p><h2>Universités en ébullition</h2><p>Des étudiants organisent des veillées silencieuses malgré l''interdiction. Les cours sont régulièrement suspendus.</p><blockquote>"Nous ne voulons ni de cette guerre ni de ce régime. Assez de sang versé !", scandent-ils.</blockquote><h2>Répression accrue</h2><p>Les arrestations se multiplient. Les peines de prison pour "propagande contre le système" atteignent parfois dix ans.</p>', 'manifestations Iran', 'anti-guerre Iran,mères soldats,répression Iran,étudiants Iran,veillées silencieuses,arrestations Iran', FALSE, 1189, 'image-25.jpg', 'reportage manifestations anti-guerre Iran', '2026-02-28 09:20:00', 10, 2),
('Iran: Interview d''un ancien négociateur nucléaire', 'Retour sur l''échec des pourparlers et l''impact sur la guerre. Un témoignage rare d''un insider.', '<h2>Pourquoi les pourparlers ont échoué</h2><p>Selon lui, les extrémistes au sein du régime ont volontairement fait capoter les accords pour maintenir un état de tension permanent.</p><h2>Le lien nucléaire-guerre</h2><p>Il affirme que l''escalade militaire sert de prétexte pour accélérer le programme nucléaire en secret.</p><blockquote>"La guerre leur permet de justifier tout ce qu''ils veulent à l''interne. C''est une stratégie de survie du régime."</blockquote><h2>Perspectives d''avenir</h2><p>Il reste pessimiste tant que les durs ne seront pas écartés du pouvoir. Un changement de paradigme est nécessaire.</p>', 'négociations nucléaires Iran', 'échec pourparlers,programme nucléaire,extrémistes Iran,escalade militaire,stratégie survie,insider Iran', TRUE, 1450, 'image-08.jpg', 'interview négociateur nucléaire Iran', '2026-03-02 11:10:00', 1, 3),
('Iran: Rapport sur les violations des droits humains', 'Documentation des exécutions sommaires, détentions arbitraires et torture. Enquête accablante.', '<h2>Exécutions sommaires</h2><p>Au moins 300 personnes ont été exécutées sans procès équitable dans les zones de conflit, selon des témoins et des images satellite.</p><h2>Détentions arbitraires massives</h2><p>Des milliers d''hommes jeunes ont été arrêtés dans des raids nocturnes. Leurs familles sont souvent sans nouvelle pendant des mois.</p><blockquote>Un rapport de l''ONU dénonce "des pratiques systématiques de torture visant à obtenir des aveux forcés".</blockquote><h2>Disparitions forcées</h2><p>De nombreux opposants présumés ont disparu. Les autorités refusent de confirmer ou d''infirmer leur détention.</p>', 'droits humains Iran', 'violations Iran,exécutions sommaires,détentions arbitraires,torture Iran,disparitions forcées,ONU Iran', TRUE, 1620, 'image-27.jpg', 'rapport droits humains Iran', '2026-03-04 14:30:00', 2, 4),
('Iran: Analyse du rôle des Gardiens de la Révolution', 'Les Gardiens, plus qu''une armée, un empire économique et politique. Leur influence dans la guerre.', '<h2>Structure parallèle de pouvoir</h2><p>Les Gardiens de la Révolution disposent de leur propre commandement, industrie militaire et réseaux économiques échappant au contrôle gouvernemental.</p><h2>Moteur de la guerre</h2><p>Ils sont les principaux artisans de l''escalade militaire. Leur puissance de feu et leur logistique surpassent celles de l''armée régulière.</p><blockquote>"Les Gardiens sont l''État dans l''État. Ils ont tout intérêt à la prolongation du conflit", analyse un chercheur.</blockquote><h2>Sanctions contournées</h2><p>Leurs entreprises fictives permettent d''importer des technologies malgré les sanctions, consolidant leur autonomie stratégique.</p>', 'Gardiens Révolution Iran', 'empire économique IRGC,structure pouvoir,escalade militaire,sanctions contournées,armée parallèle,influence politique', FALSE, 1085, 'image-05.jpg', 'analyse Gardiens Révolution Iran', '2026-03-06 08:50:00', 3, 1),
('Iran: Reportage dans les zones kurdes', 'Les Kurdes d''Iran, entre répression historique et nouveau front de guerre. Immersion dans une région oubliée.', '<h2>Villages rasés</h2><p>Dans les provinces du Kurdistan et de Kermanshah, des villages entiers ont été détruits par les bombardements. Les habitants fuient vers les montagnes.</p><h2>Identité culturelle menacée</h2><p>L''interdiction de la langue kurde dans les écoles s''est accentuée. Les déplacements forcés visent à diluer la présence kurde.</p><blockquote>"On veut effacer notre existence. Mais nous résisterons par notre culture", déclare un enseignant.</blockquote><h2>Milices locales opposées</h2><p>Des groupes armés kurdes mènent des actions de guérilla contre les forces iraniennes, ouvrant un second front dans le conflit.</p>', 'Kurdes Iran guerre', 'zones kurdes Iran,villages rasés,répression Kurdes,identité culturelle,milices kurdes,second front,déplacements forcés', FALSE, 900, 'image-10.jpg', 'reportage zones kurdes Iran', '2026-03-08 10:15:00', 4, 2),
('Iran: Interview d''un commandant de milice chiite irakienne', 'Allié de Téhéran, il livre sa vision de la guerre et le rôle des combattants étrangers.', '<h2>Fraternité d''armes avec l''Iran</h2><p>Il explique comment ses combattants reçoivent armes, formation et financement directement de Téhéran depuis des années.</p><h2>Présence sur le terrain iranien</h2><p>Il confirme que des unités irakiennes combattent aux côtés des Iraniens, notamment dans les régions frontalières.</p><blockquote>"Cette guerre est la nôtre aussi. Si l''Iran tombe, nous sommes les prochains."</blockquote><h2>Divergences stratégiques</h2><p>Il admet des désaccords occasionnels sur les priorités militaires, mais assure que la solidarité chiite prime sur tout.</p>', 'milices chiites Iran', 'commandant irakien,combattants étrangers,alliance chiite,formation militaire,financement Iran,divergences stratégiques', TRUE, 1130, 'image-22.jpg', 'interview milices chiites Iran', '2026-03-10 13:40:00', 5, 3),
('Iran: Rapport sur les cyberattaques et guerre informatique', 'Les cyber-opérations iraniennes et leurs conséquences. Infrastructure, hôpitaux, médias : cibles multiples.', '<h2>Offensive cyber contre les infrastructures</h2><p>Des attaques par ransomware ont paralysé des oléoducs et des centrales électriques. La responsabilité est attribuée à des groupes liés aux Gardiens.</p><h2>Hôpitaux ciblés</h2><p>Plusieurs établissements de santé ont subi des piratages ayant entraîné la perte de données patients et l''annulation d''opérations.</p><blockquote>"C''est une guerre hybride où le cyberespace est devenu un champ de bataille aussi meurtrier que le terrain", affirme un expert.</blockquote><h2>Propagande numérique</h2><p>L''Iran utilise également le cyber pour diffuser de la désinformation à l''international et influencer l''opinion publique.</p>', 'cyberguerre Iran', 'attaques ransomware,infrastructures paralysées,hôpitaux piratés,guerre hybride,désinformation,groupes IRGC', FALSE, 780, 'image-02.jpg', 'rapport cyberguerre Iran', '2026-03-12 09:30:00', 6, 4),
('Iran: Analyse des conséquences environnementales', 'Marées noires, pollution des sols, destruction d''écosystèmes : l''héritage toxique de la guerre.', '<h2>Frappes sur des sites industriels</h2><p>Des bombardements ont touché des raffineries et usines pétrochimiques, provoquant des fuites massives de produits toxiques dans l''air et l''eau.</p><h2>Mer Caspienne et Golfe menacés</h2><p>Des marées noires partielles ont déjà été observées. La faune marine subit des dommages irréversibles.</p><blockquote>"Il faudra des décennies pour nettoyer les dégâts environnementaux, si tant est que ce soit possible", alerte un écologiste.</blockquote><h2>Sols agricoles contaminés</h2><p>Les terres fertiles sont polluées par des métaux lourds et munitions non explosées. L''insécurité alimentaire s''aggrave.</p>', 'environnement Iran guerre', 'pollution Iran,marées noires,dégâts écologiques,sols contaminés,insécurité alimentaire,raffineries touchées', FALSE, 520, 'image-03.jpg', 'analyse environnement guerre Iran', '2026-03-14 11:00:00', 7, 1),
('Iran: Reportage sur les enfants dans la guerre', 'Ils sont les premières victimes silencieuses. Témoignages d''enfants, d''enseignants et de psychologues.', '<h2>Écoles détruites, avenir suspendu</h2><p>Plus de 500 écoles ont été endommagées ou détruites. Des milliers d''enfants n''ont plus accès à l''éducation.</p><h2>Traumatismes psychologiques profonds</h2><p>Les psychologues constatent une hausse massive des troubles du sommeil, de l''énurésie et du mutisme chez les jeunes.</p><blockquote>"Certains enfants ne parlent plus depuis qu''ils ont vu leur maison s''effondrer", explique une psychologue bénévole.</blockquote><h2>Enfants soldats dénoncés</h2><p>Des témoignages font état de recrutement forcé d''adolescents dans des milices pro-gouvernementales.</p>', 'enfants Iran guerre', 'victimes silencieuses,écoles détruites,traumatismes enfants,enfants soldats Iran,recrutement forcé,psychologues guerre', TRUE, 970, 'image-14.jpg', 'reportage enfants guerre Iran', '2026-03-16 08:20:00', 8, 2),
('Iran: Interview d''un analyste du Mossad (anonymisé)', 'Un regard extérieur sur les faiblesses iraniennes et les opportunités pour Israël.', '<h2>Coordination avec les États-Unis</h2><p>L''analyste confirme une coopération étroite en matière de renseignement pour cibler les infrastructures stratégiques iraniennes.</p><h2>L''Iran sur la corde raide</h2><p>Selon lui, le régime est plus vulnérable qu''il n''y paraît, avec des tensions internes croissantes entre factions.</p><blockquote>"Une pression soutenue pourrait provoquer un effondrement interne d''ici un an ou deux."</blockquote><h2>Limites de l''option militaire</h2><p>Il nuance cependant : une frappe directe sur les sites nucléaires serait risquée et pourrait unifier les Iraniens derrière le régime.</p>', 'Mossad Iran', 'renseignement Israël,faiblesses Iran,tensions internes,effondrement régime,option militaire,coordination USA', FALSE, 1880, 'image-10.jpg', 'interview Mossad Iran analyse', '2026-03-18 16:00:00', 9, 3),
('Iran: Rapport sur l''arsenal balistique iranien', 'État des lieux des missiles à courte, moyenne et longue portée. Capacités et limites.', '<h2>Missiles à courte portée</h2><p>Des centaines de missiles Fateh-110 et Zelzal sont en stock. Ils peuvent atteindre des cibles jusqu''à 300 km avec une précision améliorée.</p><h2>Missiles à moyenne portée</h2><p>Les Shahab-3 et Khorramshahr menacent Israël et les bases américaines dans la région. Leur fiabilité est inégale.</p><blockquote>"L''Iran possède le plus grand arsenal de missiles du Moyen-Orient, mais la moitié de ses lanceurs sont vulnérables aux frappes préventives."</blockquote><h2>Programme de missiles hypersoniques</h2><p>Téhéran affirme avoir développé un missile hypersonique. Les experts restent prudents sur sa réelle opérationnalité.</p>', 'arsenal balistique Iran', 'missiles Iran,Fateh-110,Shahab-3,missiles hypersoniques,précision missiles,lanceurs vulnérables', TRUE, 1050, 'image-26.jpg', 'rapport arsenal balistique Iran', '2026-03-20 10:45:00', 10, 4),
('Iran: Analyse de l''économie de guerre', 'Comment l''Iran finance son effort militaire malgré les sanctions. Circuits parallèles et bartering.', '<h2>Vente de pétrole déguisée</h2><p>Des flottes fantômes et transferts ship-to-ship permettent d''écouler jusqu''à 1,5 million de barils par jour vers la Chine et la Syrie.</p><h2>Or et cryptomonnaies</h2><p>L''Iran utilise des échanges d''or et des cryptomonnaies pour contourner le système bancaire international.</p><blockquote>"C''est une économie de siège qui transforme chaque crise en opportunité pour les trafiquants proches du pouvoir."</blockquote><h2>Austérité imposée aux citoyens</h2><p>L''effort de guerre est financé par la réduction drastique des subventions et l''augmentation des impôts indirects, pesant sur les classes populaires.</p>', 'économie de guerre Iran', 'financement militaire,ventes pétrole,flottes fantômes,cryptomonnaies Iran,contournement sanctions,austérité Iran', FALSE, 820, 'image-28.jpg', 'analyse économie de guerre Iran', '2026-03-22 13:15:00', 1, 1),
('Iran: Reportage sur les femmes dans la résistance civile', 'Elles sont en première ligne contre la guerre et l''oppression. Portraits de militantes iraniennes.', '<h2>Le mouvement "Femme, Vie, Liberté" perdure</h2><p>Malgré l''état de guerre, les femmes continuent d''organiser des actions de désobéissance civile : retrait du voile, manifestations silencieuses.</p><h2>Réseaux d''entraide féminins</h2><p>Des groupes clandestins apportent soutien juridique et psychologique aux familles de prisonniers politiques.</p><blockquote>"Nous luttons pour une vie digne, pas seulement contre la guerre. Les deux combats sont liés."</blockquote><h2>Répression spécifique</h2><p>Les femmes sont particulièrement ciblées par des violences sexuelles en détention pour briser leur militantisme.</p>', 'femmes Iran guerre', 'résistance civile,Femme Vie Liberté,désobéissance civile,entraide féminine,violences sexuelles,militantes Iraniennes', FALSE, 1340, 'image-17.jpg', 'reportage femmes résistance Iran', '2026-03-24 09:10:00', 2, 2),
('Iran: Interview d''un chef tribal du Baloutchistan', 'La guerre exacerbe les tensions dans une région déjà marginalisée. Un regard depuis le sud-est.', '<h2>Répression historique amplifiée</h2><p>Le chef tribal dénonce des raids quotidiens des Gardiens dans les villages baloutches, accusés de soutenir des groupes séparatistes.</p><h2>Blocus économique</h2><p>Les routes commerciales vers le Pakistan sont coupées. La population souffre de pénuries de médicaments et de carburant.</p><blockquote>"Téhéran nous traite comme des étrangers dans notre propre pays. La guerre leur sert de prétexte pour nous punir collectivement."</blockquote><h2>Recrutement forcé de jeunes</h2><p>Selon lui, des adolescents baloutches sont enlevés et contraints de rejoindre les milices pro-gouvernementales.</p>', 'Baloutchistan Iran', 'chef tribal,répression Baloutches,blocus économique,séparatistes,Gardiens Iran,recrutement forcé', TRUE, 670, 'image-16.jpg', 'interview chef tribal Baloutchistan', '2026-03-26 11:30:00', 3, 3),
('Iran: Rapport sur les mercenaires étrangers engagés', 'Afghans, Pakistanais, Soudanais : qui sont ces combattants et quel est leur rôle.', '<h2>Brigade Fatemiyoun (Afghans)</h2><p>Des milliers de réfugiés afghans chiites ont été enrôlés avec promesse de papiers et salaire. Leurs pertes sont lourdes.</p><h2>Mercenaires pakistanais</h2><p>Des groupes sunnites pakistanais recrutés pour des opérations spécifiques, mais dont la loyauté est parfois douteuse.</p><blockquote>"L''Iran externalise une partie de sa guerre pour préserver ses propres vies, mais cela crée des tensions ethniques."</blockquote><h2>Risques de déstabilisation régionale</h2><p>Le retour de ces combattants entraîne une exportation de la violence vers leurs pays d''origine.</p>', 'mercenaires Iran guerre', 'Brigade Fatemiyoun,combattants afghans,mercenaires pakistanais,externalisation guerre,tensions ethniques,déstabilisation', FALSE, 720, 'image-05.jpg', 'rapport mercenaires étrangers Iran', '2026-03-28 14:20:00', 4, 4),
('Iran: Analyse des tactiques de guérilla urbaine', 'Face à une armée conventionnelle supérieure, l''Iran développe des techniques de combat en zone urbaine.', '<h2>Milices locales intégrées</h2><p>Les Gardiens entraînent des milices civiles dans les grandes villes pour transformer les quartiers en forteresses.</p><h2>Tunnels et fortifications souterraines</h2><p>Un vaste réseau de tunnels sous Téhéran et Ispahan permet des déplacements discrets et le stockage d''armes.</p><blockquote>"La guerre urbaine est l''avenir du conflit. L''Iran s''y prépare depuis dix ans."</blockquote><h2>Drone swarm tactiques</h2><p>Des essaims de drones bon marché sont utilisés pour saturer les défenses adverses avant une attaque terrestre.</p>', 'guérilla urbaine Iran', 'milices civiles,tunnels Iran,fortifications,drone swarm,défenses adverses,tactiques combat', TRUE, 890, 'image-27.jpg', 'analyse guérilla urbaine Iran', '2026-03-30 08:40:00', 5, 1),
('Iran: Reportage sur les artistes en résistance', 'Peintres, musiciens, cinéastes : comment la culture résiste à la guerre et à la censure.', '<h2>Graffitis de nuit</h2><p>Des fresques clandestines apparaissent sur les murs des villes, dénonçant la guerre avec poésie. Leurs auteurs risquent la prison.</p><h2>Concerts secrets</h2><p>Dans des caves et garages, des musiciens jouent des morceaux interdits. Le public se passe le mot via Telegram.</p><blockquote>"Notre arme, c''est notre art. On ne peut pas nous empêcher de créer, même sous les bombes."</blockquote><h2>Cinéma de la dissidence</h2><p>Des courts-métrages tournés en cachette circulent à l''international, documentant la réalité du conflit.</p>', 'artistes Iran guerre', 'résistance culturelle,graffitis Iran,concerts secrets,cinéma dissidence,censure Iran,création clandestine', FALSE, 1150, 'image-17.jpg', 'reportage artistes résistance Iran', '2026-03-01 10:20:00', 6, 2),
('Iran: Interview d''un commandant d''unité de drones', 'Dans une base secrète, un officier des Gardiens détaille la stratégie des frappes de drones.', '<h2>Autonomie croissante</h2><p>Il explique que l''Iran produit désormais 80% des composants de ses drones localement, réduisant la dépendance aux importations.</p><h2>Cibles prioritaires</h2><p>Les infrastructures pétrolières et les centres de commandement adverses sont les cibles principales. La précision s''est améliorée.</p><blockquote>"Chaque drone coûte dix fois moins cher qu''un missile et peut faire autant de dégâts. C''est l''arme de l''avenir."</blockquote><h2>Exportation de la technologie</h2><p>Il confie que des drones iraniens sont déployés par les alliés en Irak, Syrie et Yémen.</p>', 'drones Iran combat', 'commandant drones,production locale,frappes précision,exportation drones,technologie iranienne,Gardiens drones', TRUE, 1430, 'image-06.jpg', 'interview drones Iran', '2026-03-03 13:50:00', 7, 3),
('Iran: Rapport sur les prisons secrètes', 'Enquête sur les centres de détention clandestins où disparaissent opposants et prisonniers de guerre.', '<h2>Localisations dissimulées</h2><p>Des bâtiments civils reconvertis : écoles désaffectées, sous-sols de casernes, entrepôts en zone industrielle.</p><h2>Témoignages de rescapés</h2><p>Les rares libérés décrivent des conditions inhumaines, déprivations sensorielles, électrochocs.</p><blockquote>"Ils voulaient nous faire avouer des liens avec des puissances étrangères. Certains n''en sont jamais ressortis."</blockquote><h2>Implication des Gardiens</h2><p>Tous les témoignages concordent : ces prisons sont gérées directement par l''unité de renseignement des Gardiens de la Révolution.</p>', 'prisons secrètes Iran', 'détention clandestine,Gardiens renseignement,disparitions Iran,témoignages rescapés,conditions inhumaines,opposants Iran', FALSE, 950, 'image-12.jpg', 'rapport prisons secrètes Iran', '2026-03-05 09:00:00', 8, 4),
('Iran: Analyse des soutiens internationaux', 'Russie, Chine, Corée du Nord : quelles aides concrètes à l''effort de guerre iranien.', '<h2>Transferts d''armes russes</h2><p>La Russie fournit des systèmes de défense aérienne S-400 en échange de drones Shahed. Une coopération militaire accrue.</p><h2>Rôle de la Chine</h2><p>Pékin injecte des liquidités via des achats de pétrole et investissements, mais reste prudente sur l''aide militaire directe.</p><blockquote>"La Chine veut un tampon contre l''influence américaine, mais ne souhaite pas une guerre ouverte."</blockquote><h2>Corée du Nord : coopération technique</h2><p>Des échanges documentés sur les missiles balistiques et technologies nucléaires renforcent les capacités iraniennes.</p>', 'soutiens internationaux Iran', 'Russie Iran armes,Chine Iran pétrole,Corée Nord Iran,coopération militaire,S-400 Iran,drones Shahed', TRUE, 1680, 'image-11.jpg', 'analyse soutiens internationaux Iran', '2026-03-07 11:25:00', 9, 1),
('Iran: Reportage sur les villages chiites du Liban', 'Comment la guerre en Iran est vécue au sein de la "résistance" libanaise.', '<h2>Solidarité active</h2><p>Dans la banlieue sud de Beyrouth, des collectes de fonds et de sang sont organisées pour "les frères iraniens".</p><h2>Présence militaire discrète</h2><p>Des conseillers iraniens circulent librement parmi la population. Le Hezbollah assure leur protection.</p><blockquote>"Si Téhéran tombe, nous perdons notre protecteur. Cette guerre est la nôtre."</blockquote><h2>Crainte d''une extension</h2><p>Les habitants redoutent que le conflit ne s''étende au Liban, ravivant les tensions internes et avec Israël.</p>', 'Hezbollah Iran guerre', 'villages chiites Liban,solidarité Hezbollah,conseillers iraniens,extension conflit,tensions Liban,résistance chiite', FALSE, 760, 'image-08.jpg', 'reportage Hezbollah Iran', '2026-03-09 14:45:00', 10, 2),
('Iran: Interview d''un démineur humanitaire', 'Le quotidien des équipes qui neutralisent les engins explosifs, un danger persistant après les combats.', '<h2>Des bombes qui tuent longtemps après</h2><p>Les sous-munitions et mines antipersonnel continuent de faire des victimes civiles, surtout des enfants.</p><h2>Techniques de déminage</h2><p>Il explique les protocoles dangereux, souvent entravés par le manque de matériel et les zones encore actives.</p><blockquote>"Chaque jour, on sait qu''on peut sauter. Mais si on ne le fait pas, qui le fera ?"</blockquote><h2>Formation de locaux</h2><p>Son ONG forme des villageois pour qu''ils puissent sécuriser leurs terres, une mission de long terme.</p>', 'déminage Iran', 'démineur humanitaire,sous-munitions,mines antipersonnel,victimes civiles,neutralisation explosifs,formation locaux', FALSE, 530, 'image-04.jpg', 'interview démineur Iran', '2026-03-11 10:10:00', 1, 3),
('Iran: Rapport sur les fuites de données sensibles', 'Des milliers de documents internes des Gardiens fuient. Révélations sur les opérations secrètes et la corruption.', '<h2>Opérations clandestines en Europe</h2><p>Les documents détaillent des projets d''assassinats d''opposants sur le sol européen, orchestrés depuis Téhéran.</p><h2>Corruption massive</h2><p>Des fonds destinés à l''effort de guerre ont été détournés vers des projets immobiliers de luxe pour les commandants.</p><blockquote>"La guerre est une vache à lait pour certains. Pendant que les civils meurent, eux s''enrichissent."</blockquote><h2>Listes noires</h2><p>Les fuites incluent des listes de journalistes, militants et scientifiques à "neutraliser".</p>', 'fuites données Iran', 'documents Gardiens,opérations secrètes,corruption Iran,assassinats Europe,listes noires,neutralisation opposants', TRUE, 2100, 'image-02.jpg', 'rapport fuites données Iran', '2026-03-13 15:20:00', 2, 4),
('Iran: Analyse de la fracture générationnelle', 'Jeunes contre vieille garde : comment la guerre creuse les divisions au sein de la société iranienne.', '<h2>Jeunes connectés, jeunes en révolte</h2><p>La génération Z iranienne rejette à la fois la guerre et le régime. Les réseaux sociaux amplifient leur contestation.</p><h2>Vieille garde nostalgique de la révolution</h2><p>Les aînés, souvent acquis aux Gardiens, perçoivent le conflit comme une nouvelle "défense sacrée".</p><blockquote>"Il y a deux Iran qui s''affrontent. La guerre accélère cette cassure."</blockquote><h2>Exode des compétences</h2><p>Les jeunes diplômés fuient massivement, privant le pays d''une génération entière.</p>', 'fracture générationnelle Iran', 'jeunes Iran révolte,vieille garde,défense sacrée,exode compétences,cassure sociale,génération Z', FALSE, 990, 'image-13.jpg', 'analyse fracture générationnelle Iran', '2026-03-15 08:30:00', 3, 1),
('Iran: Reportage sur les soignants en première ligne', 'Médecins et infirmiers, héros méconnus qui travaillent sous les bombes.', '<h2>Hôpitaux saturés et sous-équipés</h2><p>Les structures manquent de tout : médicaments, anesthésiants, parfois même d''électricité. Les médecins improvisent.</p><h2>Évacuations impossibles</h2><p>Faute d''ambulances et de carburant, certains blessés meurent avant d''arriver à l''hôpital.</p><blockquote>"On pleure en cachette, mais on ne peut pas s''arrêter. Chaque vie sauvée est une victoire."</blockquote><h2>Personnel soignant ciblé</h2><p>Des frappes ont visé des hôpitaux. Des médecins ont été arrêtés pour avoir soigné des blessés "du mauvais côté".</p>', 'soignants Iran guerre', 'médecins guerre,hôpitaux saturés,évacuations blessés,personnel ciblé,héros méconnus,sous-équipement', FALSE, 860, 'image-01.jpg', 'reportage soignants Iran', '2026-03-17 12:00:00', 4, 2),
('Iran: Interview d''un négociateur en otages', 'Récit de négociations tendues pour libérer des otages occidentaux, prisonniers politiques et doubles-jeux.', '<h2>Monnaie d''échange</h2><p>Les otages sont utilisés pour obtenir des levées de sanctions ou libérer des Gardiens détenus à l''étranger.</p><h2>Négociations de longue haleine</h2><p>Il raconte des mois de pourparlers secrets dans des pays tiers, avec des intermédiaires qataris et suisses.</p><blockquote>"Le régime ne recule devant aucune tactique. J''ai vu des otages libérés après des années, brisés psychologiquement."</blockquote><h2>Profils variés</h2><p>Parmi les prisonniers : journalistes, universitaires, touristes, tous utilisés comme pions géopolitiques.</p>', 'otages Iran', 'négociateur otages,prisonniers politiques,sanctions levées,intermédiaires Qatar,doubles-jeux Iran,otages occidentaux', TRUE, 1250, 'image-09.jpg', 'interview otages Iran', '2026-03-19 14:10:00', 5, 3),
('Iran: Rapport sur le patrimoine culturel en danger', 'Sites classés à l''UNESCO menacés par les bombardements et l''exploitation militaire.', '<h2>Persépolis sous menace</h2><p>Des frappes à proximité ont fait vibrer les fondations du site antique. Des experts alertent sur des dommages irréversibles.</p><h2>Museums pillés ou détruits</h2><p>Plusieurs musées régionaux ont été bombardés, avec perte d''artefacts uniques.</p><blockquote>"C''est l''identité même de l''Iran qui est attaquée. Une fois détruite, elle ne se reconstruit pas."</blockquote><h2>Patrimoine religieux</h2><p>Des mosquées et mausolées séculaires sont transformés en dépôts d''armes, les exposant à des représailles.</p>', 'patrimoine Iran guerre', 'Persépolis menace,sites UNESCO,musées détruits,artefacts uniques,patrimoine religieux,identité iranienne', FALSE, 650, 'image-30.jpg', 'rapport patrimoine Iran', '2026-03-21 09:45:00', 6, 4),
('Iran: Analyse des divisions au sein du clergé', 'Le pouvoir religieux iranien n''est pas unanime. Qui soutient la guerre, qui l''oppose secrètement.', '<h2>Clergé conservateur pro-guerre</h2><p>Autour du Guide suprême, une faction justifie le conflit par la lutte contre "l''arrogance occidentale".</p><h2>Clergé réformateur étouffé</h2><p>Des ayatollahs réformateurs sont assignés à résidence pour avoir appelé à la fin des hostilités.</p><blockquote>"Certains religieux rappellent que l''islam interdit de tuer des innocents. Mais ils sont réduits au silence."</blockquote><h2>Séminaires en ébullition</h2><p>Dans les villes saintes de Qom et Machhad, des débats houleux opposent étudiants et professeurs.</p>', 'clergé Iran guerre', 'divisions clergé,Guide suprême,ayatollahs réformateurs,assignés résidence,Qom débat,islam guerre', FALSE, 720, 'image-12.jpg', 'analyse clergé Iran', '2026-03-23 11:50:00', 7, 1),
('Iran: Reportage sur les pompiers face aux bombes', 'Ils éteignent les feux sous les raids aériens. Des héros sans armes.', '<h2>Interventions impossibles sans protection</h2><p>Les pompiers manquent de casques, de camions. Ils risquent leur vie sans équipement adapté.</p><h2>Zones industrielles en feu</h2><p>Les incendies dans les usines chimiques créent des nuages toxiques. Les pompiers subissent des intoxications graves.</p><blockquote>"On nous demande d''éteindre des feux pendant qu''ils bombardent à côté. C''est un enfer."</blockquote><h2>Reconnaissance tardive</h2><p>Leur héroïsme est enfin célébré dans les médias sociaux, car le régime évite d''admettre l''ampleur des dégâts.</p>', 'pompiers Iran guerre', 'héros sans armes,incendies industrie,nuages toxiques,raids aériens,reconnaissance tardive,pompiers risques', FALSE, 580, 'image-24.jpg', 'reportage pompiers Iran', '2026-03-25 08:15:00', 8, 2),
('Iran: Interview d''un trafiquant d''armes', 'Dans l''ombre, il raconte comment le marché noir alimente tous les belligérants. Témoignage sous couvert d''anonymat.', '<h2>Réseaux transfrontaliers</h2><p>De la Libye au Pakistan, des routes historiques réactivées pour faire circuler armes et munitions.</p><h2>Double jeu avec les Gardiens</h2><p>Il affirme livrer à la fois des armes aux Gardiens et à des groupes rebelles. "L''argent n''a pas d''odeur."</p><blockquote>"Tant qu''il y a la guerre, je travaille. Et ça ne finira jamais."</blockquote><h2>Armes de la Seconde Guerre mondiale</h2><p>Certaines armes récupérées datent des années 1940, montrant le niveau de désespoir des combattants.</p>', 'trafiquants armes Iran', 'marché noir Iran,réseaux transfrontaliers,Gardiens trafic,armes anciennes,double jeu,approvisionnement', TRUE, 1330, 'image-16.jpg', 'interview trafiquant armes Iran', '2026-03-27 13:30:00', 9, 3),
('Iran: Rapport sur l''état des forces navales', 'Face aux menaces en mer d''Oman et Golfe, quelles sont les capacités réelles de la marine iranienne.', '<h2>Petits navires rapides et tactiques asymétriques</h2><p>Une flotte de centaines de vedettes lance-missiles pouvant mener des attaques en essaim.</p><h2>Sous-marins de poche</h2><p>Des mini-sous-marins adaptés au détroit d''Ormuz, capables de poser des mines discrètement.</p><blockquote>"L''Iran ne cherche pas à gagner une bataille navale classique, mais à rendre le Golfe ingérable pour ses adversaires."</blockquote><h2>Menace sur les tankers</h2><p>Des tentatives de saisie de navires marchands se sont multipliées, visant à faire monter les prix du pétrole.</p>', 'forces navales Iran', 'vedettes missiles,mini-sous-marins,détroit Ormuz,attaques essaim,menace tankers,marine asymétrique', FALSE, 920, 'image-29.jpg', 'rapport forces navales Iran', '2026-03-29 15:00:00', 10, 4);

